### ISSUE TITLE
基于Flex的简易布局代码

### ISSUE THREAD

**Issue by twn39** [twn39/code#149]
```stylus
.flex-row
  flex: 1
  display: flex
  flex-direction: row
  flex-wrap: wrap
.flex-row-reverse
  flex: 1
  display: flex
  flex-direction: row-reverse
  flex-wrap: wrap
.flex-column
  flex: 1
  display: flex
  flex-direction: column
  flex-wrap: wrap
.flex-column-reverse
  flex: 1
  display: flex
  flex-direction: column-reverse
  flex-wrap: wrap
.flex-1
  display: flex
  flex: 1
.flex-2
  display: flex
  flex: 2
.flex-3
  display: flex
  flex: 3
.flex-4
  display: flex
  flex: 4
.flex-5
  display: flex
  flex: 5
.flex-6
  display: flex
  flex: 6
.flex-7
  display: flex
  flex: 7
.flex-8
  display: flex
  flex: 8
.flex-9
  display: flex
  flex: 9
.flex-10
  display: flex
  flex: 10
.flex-11
  display: flex
  flex: 11
.justify-flex-start
  justify-content: flex-start
.justify-flex-end
  justify-content: flex-end
.justify-center
  justify-content: center
.justify-space-between
  justify-content: space-between
.justify-space-around
  justify-content: space-around
.align-flex-start
  align-items: flex-start
.align-flex-end
  align-items: flex-end
.align-center
  align-items: center
.align-baseline
  align-items: baseline
.align-stretch
  align-items: stretch
```

**Comment by twn39** [comment]
CSS代码：

```css
.flex-row {
  flex: 1;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}
.flex-row-reverse {
  flex: 1;
  display: flex;
  flex-direction: row-reverse;
  flex-wrap: wrap;
}
.flex-column {
  flex: 1;
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
}
.flex-column-reverse {
  flex: 1;
  display: flex;
  flex-direction: column-reverse;
  flex-wrap: wrap;
}
.flex-1 {
  display: flex;
  flex: 1;
}
.flex-2 {
  display: flex;
  flex: 2;
}
.flex-3 {
  display: flex;
  flex: 3;
}
.flex-4 {
  display: flex;
  flex: 4;
}
.flex-5 {
  display: flex;
  flex: 5;
}
.flex-6 {
  display: flex;
  flex: 6;
}
.flex-7 {
  display: flex;
  flex: 7;
}
.flex-8 {
  display: flex;
  flex: 8;
}
.flex-9 {
  display: flex;
  flex: 9;
}
.flex-10 {
  display: flex;
  flex: 10;
}
.flex-11 {
  display: flex;
  flex: 11;
}
.justify-flex-start {
  justify-content: flex-start;
}
.justify-flex-end {
  justify-content: flex-end;
}
.justify-center {
  justify-content: center;
}
.justify-space-between {
  justify-content: space-between;
}
.justify-space-around {
  justify-content: space-around;
}
.align-flex-start {
  align-items: flex-start;
}
.align-flex-end {
  align-items: flex-end;
}
.align-center {
  align-items: center;
}
.align-baseline {
  align-items: baseline;
}
.align-stretch {
  align-items: stretch;
}
```
