### ISSUE TITLE
CSS动画

### ISSUE THREAD

**Issue by twn39** [twn39/code#164]
闪烁效果，可用于消息提醒，红点闪烁：

```css
.notice {
    animation: 1.2s cubic-bezier(.45,.05,.55,.95) 0s infinite alternate flashing;
}

@keyframes flashing {
    from {
        opacity: 0;
    }

    to {
        opacity: 1;
    }
}
```

**Comment by twn39** [comment]
### Ease out 可用于按钮移入移除的效果：

```css
.button {
    border: 2px solid #e14346;
    padding: 6px 40px;
    background: none;
    font-size: 1.2rem;
    font-weight: bold;
    color: #e14346;
    transition-property: background, color;
    transition-duration: 0.5s;
    transition-timing-function: ease-out;
}

.button:hover {
    border: 2px solid #e14346;
    padding: 6px 40px;
    background: #e14346;
    font-size: 1.2rem;
    color: #fff;
    transition-property: background, color;
    transition-duration: 0.5s;
    transition-timing-function: ease-out;
}
```
