### ISSUE TITLE
CSS 使用 clip-path 属性裁剪元素

### ISSUE THREAD

**Issue by twn39** [twn39/code#320]
CSS 的 `clip-path` 属性可以对元素进行裁剪，是特定区域展示在页面上，`clip-path` 支持圆形（circle），椭圆（ellipse），多边形（polygon）和 SVG 路径。

以 Angular 为例：

```html
<div class="main">
  <div class="rect">
    <div class="info" (click)="handleClick()" [ngStyle]="fadeStyle">
      <span>🎉</span>
    </div>
  </div>
</div>
```

```scss
.main {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  padding-top: 10rem;
  .rect {
    width: 300px;
    height: 200px;
    box-shadow: 0 0 3px rgba(0, 0, 0, 0.1);
    background: rebeccapurple;
    border-radius: 6px;
    position: relative;
    .info {
      right: 0;
      background: #90d921;
      height: 100%;
      width: 100%;
      position: relative;
      cursor: pointer;
      border-top-left-radius: 6px;
      span {
        padding: 0.5rem;
        display: inline-block;
      }
    }
  }
}
```

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'ngplayground';

  toggle = false;

  handleClick() {
    this.toggle = !this.toggle;
  }

  get fadeStyle() {
    return this.toggle
      ? {
        'clip-path': 'circle(400px at 0 0)',
        transition: 'opacity 0.2s ease, clip-path 0.2s ease',
        opacity: '1',
      }
      : {
        'clip-path': 'circle(50px at 0 0)',
        transition: 'opacity 0.2s ease, clip-path 0.2s ease',
        opacity: '0.8',
      };
  }
}
```
