### ISSUE TITLE
Traefik 配置

### ISSUE THREAD

**Issue by twn39** [twn39/code#401]
安装 traefik，文件：`docker-compose.yml` ：

```yml
version: '3'

services:
  traefik-server:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8030:8080"
    networks:
      - worknet
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  worknet:
    name: worknet
```

启动：

```
docker-compose up -d traefik-server
```
