### ISSUE TITLE
SD scripts flux.dev 训练配置文件

### ISSUE THREAD

**Issue by twn39** [twn39/code#434]
配置文件：

```toml
output_dir = "/root/autodl-tmp/flux/model"
output_name = "simon_bailly_flux"
train_data_dir = "/root/train_data"
logging_dir = "/root/tf-logs"

pretrained_model_name_or_path = "/root/autodl-tmp/flux1-dev.safetensors"
ae = "/root/autodl-tmp/ae.safetensors"
clip_l = "/root/autodl-tmp/clip_l.safetensors"
t5xxl = "/root/autodl-tmp/t5xxl_fp16.safetensors"

max_train_steps = 4600
train_batch_size = 1
epoch = 10
unet_lr = 0.0001
resolution = "1024,1024"
discrete_flow_shift = 3.1582
optimizer_args = ["weight_decay=0.01","eps=1e-08","betas=(0.9, 0.999)"]
optimizer_type = "AdamW8bit"
network_dim = 32
network_alpha = 16

bucket_no_upscale = true
bucket_reso_steps = 64
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
fp8_base = true
gradient_checkpointing = true
guidance_scale = 1.0
highvram = true
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_bucket_reso = 2048
max_data_loader_n_workers = 2
max_grad_norm = 1
max_timestep = 1000
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "bf16"
model_prediction_type = "raw"
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_module = "networks.lora_flux"
network_train_unet_only = true
persistent_data_loader_workers = 1
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
sdpa = true
seed = 42
t5xxl_max_token_length = 512
timestep_sampling = "sigmoid"
sigmoid_scale = 1.0
noise_offset = 0.03
```

训练命令：

```bash
accelerate launch --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 /root/sd-scripts/flux_train_network.py --config_file /root/config_lora.toml
```

数据集文件命名：`repeats_class instance`, 例如：`10_blindbox blindbox`

其它具体参数参考：https://github.com/kohya-ss/sd-scripts/tree/sd3?tab=readme-ov-file#flux1-training
