### ISSUE TITLE
Memcache代理twemproxy设置

### ISSUE THREAD

**Issue by twn39** [twn39/code#72]
项目：https://github.com/twitter/twemproxy

**Comment by twn39** [comment]
## 安装 

1. 下载源代码，编译安装
2. Ubuntu PPA

**Comment by twn39** [comment]
## Memcache

新建配置文件`/etc/nutcracker/nutcracker.yml`:

```
gamma:
  listen: 127.0.0.1:22123
  hash: fnv1a_64
  distribution: ketama
  timeout: 400
  backlog: 1024
  preconnect: true
  auto_eject_hosts: true
  server_retry_timeout: 2000
  server_failure_limit: 3
  servers:
   - 127.0.0.1:11212:1
   - 127.0.0.1:11211:1
```
