### ISSUE TITLE
Ansible Playbook

### ISSUE THREAD

**Issue by twn39** [twn39/code#79]
```yml
---
- hosts: web
  remote_user: ubuntu
  sudo: yes

  tasks:
    - name: Init Server
      command: apt-get update

    - name: Install useful softwave
      apt: name={{ item }} state=present
      with_items:
        - curl
        - git
        - htop
        - tree
        - python-mysqldb

    - name: Install Nginx.
      apt: name=nginx state=present

    - name: Install PHP5.
      apt: name={{ item }} state=present
      with_items:
        - php5
        - php5-curl
        - php5-cli
        - php5-mcrypt
        - php5-fpm
        - php5-mysql
        - php5-pgsql
        - php5-memcached
        - php5-redis
        - php5-mongo
        - php5-gd
        - php5-apcu

    - name: Install MySQL
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Remove the MySQL test database.
      mysql_db: db=test state=absent

    - name: Install Redis
      apt: name={{ item }} state=present
      with_items:
        - redis-server
        - redis-tools

    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run Composer installer.
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move Composer into globally-accessible location.
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer
```
